App\Domain\Backup\WriteModel\Author:
    type: entity
    table: users

    id:
        id:
            type: guid
            generator:
                strategy: UUID

    fields:
        email:
            type: string
