doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Backup\WriteModel:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Backup/WriteModel'
                prefix: 'App\Domain\Backup\WriteModel'
                alias: Backup

            App\Domain\Backup\ValueObject:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Backup/ValueObject'
                prefix: 'App\Domain\Backup\ValueObject'
                alias: BackupVO

            App\Domain\Users\WriteModel:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Users/WriteModel'
                prefix: 'App\Domain\Users\WriteModel'
                alias: Users

            App\Domain\Users\ValueObject:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Users/ValueObject'
                prefix: 'App\Domain\Users\ValueObject'
                alias: UsersVO

            App\Domain\Users\View:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Users/View'
                prefix: 'App\Domain\Users\View'
                alias: UsersViews

            App\Domain\Users\Collection:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/Users/Collection'
                prefix: 'App\Domain\Users\Collection'
                alias: UsersCOLLECTION
