security:
    encoders:
        App\Domain\Users\View\UserView:
            algorithm: sha256
            hash_algorithm: sha256
            encode_as_base64: false
            key_length: 64
            iterations: "%env(PASSWD_ITERATIONS)%"

    providers:
        users:
            entity:
                class: 'App\Domain\Users\View\UserView'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        json_login:
            pattern: ^/api/v1/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/v1/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/v1
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1,       roles: IS_AUTHENTICATED_FULLY }
