frontend_controllers:
    resource: ../../src/Infrastructure/Frontend/Controller/
    type: annotation

backup_controllers:
    prefix: "/api/v1"
    resource: ../../src/Infrastructure/Backup/Controller/
    type: annotation

user_controllers:
    prefix: "/api/v1"
    resource: ../../src/Infrastructure/User/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
