version: org.riotkit.rkd/yaml/v1
imports: []
tasks:
    :dev:up:
        description: Setup development environment requirements
        steps: |
            %RKD% :docker:up :symfony:dev-server:up

    :docker:up:
        become: root
        description: Runs a dockerized environment
        steps: |
            docker-compose -p s3pb -f .devops/docker-compose.yml up -d

    :docker:cleanup:
        become: root
        description: Remove docker environment
        steps: |
            docker-compose -p s3pb -f .devops/docker-compose.yml down -v

    :symfony:dev-server:up:
        description: Runs a development server
        steps: symfony local:server:start --allow-http --no-tls

    :dev:php8:
        become: root
        description: Run development webserver on PHP 8
        steps: |
            cp -pr ~/.symfony .devops/symfony
            docker run --rm --name php_8 \
                --entrypoint /bin/sh \
                -v $(pwd):/var/www/html \
                -e HOME=/var/www/html \
                -w /var/www/html \
                -p 8009:8000 \
                -u 1000:1000 php:8.0.0beta2-cli-alpine \
                -c "set -x; rm -rf var/cache .symfony .devops/symfony/cache .devops/symfony/php .devops/symfony/var; .devops/symfony/bin/symfony serve --allow-http --dir=\$(pwd)"

    :psql:
        description: Get into PostgreSQL shell
        steps: |
            psql -h 127.0.0.1 -U postgres postgres

    :test:behat:
        description: Run Behat tests
        steps: |
            set -o allexport; . .env.test; set +o allexport;
            ./vendor/bin/behat
