version: "3.4"

services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        ports:
            - 5432:5432

