parameters:
    env(PASSWD_ALGORITHM): 'sha256'
    env(PASSWD_ITERATIONS): '90000'
    env(JWT_LIFETIME): '+1 hour'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            # @todo: Exclude classes that should not be in container
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Domain/{Storage,Users,Security,Backup,Common}/WriteModel/'
            - '../src/Domain/{Storage,Users,Security,Backup,Common}/Collection'

    App\Infrastructure\Common\Event\Subscriber\DomainValidationErrorSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\Backup\Controller\:
        resource: '../src/Infrastructure/Backup/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Infrastructure\Frontend\Controller\:
        resource: '../src/Infrastructure/Frontend/Controller/'
        tags: ['controller.service_arguments']

    App\Infrastructure\User\Controller\:
        resource: '../src/Infrastructure/User/Controller/'
        tags: ['controller.service_arguments']

    command_handlers:
        namespace: App\Application\Command\Handler\
        resource: '%kernel.project_dir%/src/Application/Command/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers:
        namespace: App\Application\Query\Handler\
        resource: '%kernel.project_dir%/src/Application/Query/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    event_handlers:
        namespace: App\Application\Event\Handler\
        resource: '%kernel.project_dir%/src/Application/Event/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: event.bus }

    App\Domain\Common\Service\CommandBusInterface:
        class: App\Infrastructure\Common\Service\CommandBus
        arguments:
            $bus: '@command.bus'

    App\Domain\Common\Service\QueryBusInterface:
        class: App\Infrastructure\Common\Service\QueryBus
        arguments:
            $bus: '@query.bus'

    App\Domain\Common\Service\EventBusInterface:
        class: App\Infrastructure\Common\Service\EventBus
        arguments:
            $bus: '@event.bus'

    #
    # Configurations (from environment variables)
    #
    App\Domain\Users\Configuration\PasswordHashingConfiguration:
        arguments:
            $algorithm: '%env(PASSWD_ALGORITHM)%'
            $iterations: '%env(int:PASSWD_ITERATIONS)%'

    App\Domain\Security\Configuration\ApplicationInfo:
        arguments:
            $environmentType: '%kernel.environment%'

    App\Domain\Security\Configuration\JWTConfiguration:
        arguments:
            $lifetime: '%env(JWT_LIFETIME)%'
